
  <footer class="page-footer light-blue">
    <div class="container">
      <div class="row">
        <div class="col l10 s12">
          <h5 class="white-text"><?=$this->config['name']?></h5>
          <p class="grey-text text-lighten-4">I am a solo developer hoping to create the biggest and fastest next PHP template engine. Having been a developer for several years and acknowledging Smarty's existance through all of it. I am confident that I can build the fastest template engine!</p>


        </div>
        <div class="col l2 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://github.com/CameronCT">GitHub</a></li>
            <li><a class="white-text" href="mailto:admin@nerdsthatcode.com">Email</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        &copy; <?=$this->config['name']?> 2016. Made by <a class="blue-text text-lighten-3" href="https://github.com/CameronCT/ezPHP" alt="GitHub"><i class="fa fa-github fa-lg"></i> CameronCT</a>
        <span class="right">
          <?=$this->load?> seconds
        </span>
      </div>
    </div>
  </footer>


  <!-- jQuery -->
  <script src="<?=CDN::for('static')?>/js/jquery.min.js"></script>

  <!-- Materialize -->
  <script src="<?=CDN::for('static')?>/js/materialize.js"></script>

  <!-- App -->
  <script src="<?=CDN::for('static')?>/js/init.js"></script>

  </body>
</html>
