    <!-- FOOTER -->
      <footer>
        <p class="float-right">This page loaded in <?=$this->load?> seconds.</p>
        <p>&copy; 2017 <?=$this->config['name']?> &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->


    <!-- jQuery -->
    <script src="<?=CDN::for('static', '/js/jquery.min.js')?>"></script>

    <!-- Bootstrap v4 -->
    <script src="<?=CDN::for('static', '/js/bootstrap.min.js')?>"></script>

    <!-- Holder -->
    <script src="<?=CDN::for('static', '/js/holder.min.js')?>"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?=CDN::for('static', '/js/ie10-viewport-bug-workaround.js')?>"></script>
  </body>
</html>
