<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title><?=$this->config['name']?> - <?=$this->title?></title>

    <!-- Bootstrap v4 -->
    <link href="<?=CDN::for('static', '/css/bootstrap.min.css')?>" rel="stylesheet">

    <!-- App -->
    <link href="<?=CDN::for('static', '/css/app.css')?>" rel="stylesheet">
  </head>
  <body>