  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center light-blue-text"><?=$this->config['name']?></h1>
      <div class="row center">
        <h5 class="header col s12 light white-text">SmartyPHP inspired framework built for PHP 7 exclusively.</h5>
      </div>
      <div class="row center">
        <a href="https://github.com/CameronCT/ezPHP" id="download-button" class="btn-large waves-effect waves-light blue">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>

  <div class="container-fluid bg">
    <?=$this->render('alerts')?>
    <div class="container">
      <div class="section">

        <!--   Icon Section   -->
        <div class="row">
          <?php foreach($this->data as $data): ?>
          <div class="col s12 m4">
            <div class="icon-block">
              <h2 class="center light-blue-text"><i class="material-icons"><?=$data['icon']?></i></h2>
              <h5 class="center"><?=$data['title']?></h5>

              <p class="light"><?=$data['body']?></p>
            </div>
          </div>
          <?php endforeach; ?>
        </div>

      </div>
    </div>
  </div>